vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        pin_image:
            uri_prefix: /imageSave/pins
            upload_destination: "%kernel.project_dir%/public/imageSave/pins"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
