vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        pin_image:
            uri_prefix: /uploads/pins
            upload_destination: "%kernel.project_dir%/imageSave/pins"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
